# Generated by Django 3.2.7 on 2021-10-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import img_ocean.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(upload_to=img_ocean.models.img_path, verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Upload datetime')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
