# Generated by Django 3.1.7 on 2021-10-02 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import img_ocean.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('img_ocean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to=img_ocean.models.img_path, verbose_name='original image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='upload datetime')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
