# Generated by Django 3.1.7 on 2021-10-02 13:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('img_ocean', '0002_auto_20211002_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('owner', 'title')},
        ),
    ]
