# Generated by Django 3.1.7 on 2021-10-02 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_ocean', '0003_auto_20211002_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, verbose_name='plan title')),
                ('img_height', models.CharField(max_length=255, validators=[django.core.validators.int_list_validator, django.core.validators.MinValueValidator(1, 'image heights have to be > 0')], verbose_name='image height')),
                ('orignal_exists', models.BooleanField(default=False, verbose_name='allow original image access')),
                ('expiring_exists', models.BooleanField(default=False, verbose_name='allow to generate expiring links')),
            ],
        ),
    ]
