# Generated by Django 3.1.7 on 2021-10-04 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('img_ocean', '0003_auto_20211003_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img_height', models.IntegerField(default=0, verbose_name='image height')),
                ('original_img', models.BooleanField(default=False, verbose_name='original image height?')),
                ('expires_on', models.DateTimeField(verbose_name='expires on')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='img_ocean.image')),
            ],
        ),
    ]
