# Generated by Django 3.1.7 on 2021-10-02 14:47

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('img_ocean', '0004_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='img_height',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('[1-9]\\d*(?:,[1-9]\\d*)*\\Z'), code='invalid', message='List must consist of comma separated positive integers')], verbose_name='image height'),
        ),
    ]
