# Generated by Django 3.1.7 on 2021-10-02 14:52

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('img_ocean', '0005_auto_20211002_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='img_height',
        ),
        migrations.AddField(
            model_name='plan',
            name='img_heights',
            field=models.CharField(default=1, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[1-9]\\d*(?:,[1-9]\\d*)*\\Z'), code='invalid', message='List must consist of comma separated positive integers')], verbose_name='image heights'),
            preserve_default=False,
        ),
    ]
