# Generated by Django 3.1.7 on 2021-10-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_ocean', '0006_auto_20211002_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='orignal_exists',
            new_name='original_exists',
        ),
    ]
